"""init

Revision ID: 37df14b28421
Revises: 
Create Date: 2023-03-14 22:42:59.800165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37df14b28421'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_categories',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('is_publish', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toppings',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foods',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('is_special', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('is_vegan', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('is_publish', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['food_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topping_food',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('food_id', sa.BIGINT(), nullable=False),
    sa.Column('topping_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['topping_id'], ['toppings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('unique_user_role_pare_id', 'topping_food', ['food_id', 'topping_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_user_role_pare_id', table_name='topping_food')
    op.drop_table('topping_food')
    op.drop_table('foods')
    op.drop_table('toppings')
    op.drop_table('food_categories')
    # ### end Alembic commands ###
